import os
import base64


def save_pcap_from_base64(filename, pcap_file_base64, dir = None):
    """
    Returns number of bytes saved.

    :param filename:
    :param pcap_file_base64:
    :return:
    """

    if dir:
        file_path = os.path.join(dir, filename)
    else :
        file_path = os.path.join(os.getcwd(), filename)

    with open( file_path, "wb") as pcap_file:
        nb = pcap_file.write(base64.b64decode(pcap_file_base64))
        return nb

if __name__ == '__main__':

    #pcap_msg = {"_type": "analysis.interop.testcase.analyze", "_api_version": "0.1.20", "file_enc": "pcap_base64", "filename": "TD_COAP_CORE_02.pcap", "testcase_id": "TD_COAP_CORE_02", "testcase_ref": "http://doc.f-interop.eu/tests/TD_COAP_CORE_02_v01", "value": "1MOyoQIABAAAAAAAAAAAAMgAAABlAAAAFFgxWT17DAA5AAAAOQAAAGALFPcAERFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAKx9BYzABHyMEAEAA20dGVzdBRYMVlVewwAkAAAAJAAAABgAAAAAGg6//6AAAAAAAAAAAAAAAAAAAO7uwAAAAAAAAAAAAAAAAABiQAuaAAAAAC7uwAAAAAAAAAAAAAAAAACu7sAAAAAAAAAAAAAAAAAAgQIAAAAAAAAYAsU9wAREUC7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAArH0FjMAEfIwQAQADbR0ZXMUWDFZXnsMADkAAAA5AAAAYAsU9wARET+7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAArH0FjMAEfIwQAQADbR0ZXN0F1gxWV5jAQA5AAAAOQAAAGALFPcAERFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAKx9BYzABHyMEAEAA20dGVzdBdYMVltYwEAkAAAAJAAAABgAAAAAGg6//6AAAAAAAAAAAAAAAAAAAO7uwAAAAAAAAAAAAAAAAABiQAuaAAAAAC7uwAAAAAAAAAAAAAAAAACu7sAAAAAAAAAAAAAAAAAAgQIAAAAAAAAYAsU9wAREUC7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAArH0FjMAEfIwQAQADbR0ZXMXWDFZdGMBADkAAAA5AAAAYAsU9wARET+7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAArH0FjMAEfIwQAQADbR0ZXN0G1gxWX+yCQA5AAAAOQAAAGALFPcAERFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAKx9BYzABHyMEAEAA20dGVzdBtYMVmNsgkAkAAAAJAAAABgAAAAAGg6//6AAAAAAAAAAAAAAAAAAAO7uwAAAAAAAAAAAAAAAAABiQAuaAAAAAC7uwAAAAAAAAAAAAAAAAACu7sAAAAAAAAAAAAAAAAAAgQIAAAAAAAAYAsU9wAREUC7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAArH0FjMAEfIwQAQADbR0ZXMbWDFZlrIJADkAAAA5AAAAYAsU9wARET+7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAArH0FjMAEfIwQAQADbR0ZXN0"}
    #pcap_msg = {"_type": "analysis.interop.testcase.analyze", "_api_version": "0.1.20", "file_enc": "pcap_base64",
     # "filename": "TD_COAP_CORE_01.pcap", "testcase_id": "TD_COAP_CORE_01",
     # "testcase_ref": "http://doc.f-interop.eu/tests/TD_COAP_CORE_01_v01",
     # "value": "1MOyoQIABAAAAAAAAAAAAMgAAABlAAAAOGUxWeVwDgA5AAAAOQAAAGANAhcAERFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAALURRYzABHMiUABA2a0dGVzdDhlMVn+cA4AkAAAAJAAAABgAAAAAGg6//6AAAAAAAAAAAAAAAAAAAO7uwAAAAAAAAAAAAAAAAABiQBBRgAAAAC7uwAAAAAAAAAAAAAAAAACu7sAAAAAAAAAAAAAAAAAAgQIAAAAAAAAYA0CFwAREUC7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAAtRFFjMAEcyJQAEDZrR0ZXM4ZTFZCHEOADkAAAA5AAAAYA0CFwARET+7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAAtRFFjMAEcyJQAEDZrR0ZXN0O2UxWRgnBAA5AAAAOQAAAGANAhcAERFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAALURRYzABHMiUABA2a0dGVzdDtlMVkmJwQAkAAAAJAAAABgAAAAAGg6//6AAAAAAAAAAAAAAAAAAAO7uwAAAAAAAAAAAAAAAAABiQBBRgAAAAC7uwAAAAAAAAAAAAAAAAACu7sAAAAAAAAAAAAAAAAAAgQIAAAAAAAAYA0CFwAREUC7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAAtRFFjMAEcyJQAEDZrR0ZXM7ZTFZLicEADkAAAA5AAAAYA0CFwARET+7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAAtRFFjMAEcyJQAEDZrR0ZXN0P2UxWQ0kDgA5AAAAOQAAAGANAhcAERFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAALURRYzABHMiUABA2a0dGVzdD9lMVkcJA4AkAAAAJAAAABgAAAAAGg6//6AAAAAAAAAAAAAAAAAAAO7uwAAAAAAAAAAAAAAAAABiQBBRgAAAAC7uwAAAAAAAAAAAAAAAAACu7sAAAAAAAAAAAAAAAAAAgQIAAAAAAAAYA0CFwAREUC7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAAtRFFjMAEcyJQAEDZrR0ZXM/ZTFZJCQOADkAAAA5AAAAYA0CFwARET+7uwAAAAAAAAAAAAAAAAABu7sAAAAAAAAAAAAAAAAAAtRFFjMAEcyJQAEDZrR0ZXN0"}

    # pcap_msg = {"_type": "sniffing.getlastcapture.reply", "_api_version": "0.1.20", "ok": 'true', "file_enc": "pcap_base64",
    #  "filename": "TD_COAP_CORE_01.pcap",
    #  "value": "1MOyoQIABAAAAAAAAAAAAMgAAABlAAAAi4sxWUv2CQBPAAAATwAAAGAN14kAJxFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAK5aRYzACdN / UADAty0dGVzdBEp / zx2YWx1ZT50ZXN0PC92YWx1ZT6LizFZYPYJAKAAAACgAAAAYAAAAAB4Ov / +gAAAAAAAAAAAAAAAAAADu7sAAAAAAAAAAAAAAAAAAYkAPAkAAAAAu7sAAAAAAAAAAAAAAAAAAru7AAAAAAAAAAAAAAAAAAIECgAAAAAAAGAN14kAJxFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAK5aRYzACdN / UADAty0dGVzdBEp / zx2YWx1ZT50ZXN0PIuLMVlp9gkATwAAAE8AAABgDdeJACcRP7u7AAAAAAAAAAAAAAAAAAG7uwAAAAAAAAAAAAAAAAACuWkWMwAnTf1AAwLctHRlc3QRKf88dmFsdWU + dGVzdDwvdmFsdWU + jYsxWRUKDQBPAAAATwAAAGAN14kAJxFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAK5aRYzACdN / UADAty0dGVzdBEp / zx2YWx1ZT50ZXN0PC92YWx1ZT6NizFZKAoNAKAAAACgAAAAYAAAAAB4Ov / +gAAAAAAAAAAAAAAAAAADu7sAAAAAAAAAAAAAAAAAAYkAPAkAAAAAu7sAAAAAAAAAAAAAAAAAAru7AAAAAAAAAAAAAAAAAAIECgAAAAAAAGAN14kAJxFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAK5aRYzACdN / UADAty0dGVzdBEp / zx2YWx1ZT50ZXN0PI2LMVkwCg0ATwAAAE8AAABgDdeJACcRP7u7AAAAAAAAAAAAAAAAAAG7uwAAAAAAAAAAAAAAAAACuWkWMwAnTf1AAwLctHRlc3QRKf88dmFsdWU + dGVzdDwvdmFsdWU + kosxWbHrAwBPAAAATwAAAGAN14kAJxFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAK5aRYzACdN / UADAty0dGVzdBEp / zx2YWx1ZT50ZXN0PC92YWx1ZT6SizFZxusDAKAAAACgAAAAYAAAAAB4Ov / +gAAAAAAAAAAAAAAAAAADu7sAAAAAAAAAAAAAAAAAAYkAPAkAAAAAu7sAAAAAAAAAAAAAAAAAAru7AAAAAAAAAAAAAAAAAAIECgAAAAAAAGAN14kAJxFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAAK5aRYzACdN / UADAty0dGVzdBEp / zx2YWx1ZT50ZXN0PJKLMVnP6wMATwAAAE8AAABgDdeJACcRP7u7AAAAAAAAAAAAAAAAAAG7uwAAAAAAAAAAAAAAAAACuWkWMwAnTf1AAwLctHRlc3QRKf88dmFsdWU + dGVzdDwvdmFsdWU +"}
    # save_pcap_from_base64('test.pcap', pcap_msg['value'])

    base_64_pcap_value='1MOyoQIABAAAAAAAAAAAAMgAAABlAAAASJQxWTqkAwA5AAAAOQAAAGAOcR8AERFAu7sAAAAAAAAAAAAAAAAAAbu7AAAAAAAAAAAAAAAAAALk2RYzABGuhFAEANS0dGVzdA=='
    save_pcap_from_base64('test.pcap',base_64_pcap_value)


